title: Harry Herman # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  <br>
  <a href="https://www.linkedin.com/in/harry-herman/">LinkedIn</a> 
  <br>
  <a href="https://github.com/hsh423/hsh423.github.io/blob/master/images/Harry%20Herman%20Resume.pdf">Resume</a>  
  <br>
  <a href="https://bowen.finance/" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://github.com/hsh423">GitHub</a>  
  
theme: jekyll-theme-midnight
